### ISSUE TITLE
+1 country code not showing any country flag

### ISSUE THREAD

**Issue by hameeedurrehman** [omeralpi/shadcn-phone-input#44]
While writing +1 country code in Input field and search, it does not show any country flag
![image](https://github.com/user-attachments/assets/9186a170-fd54-4941-93bf-f4fe16cb2571)

System Info
SYSTEM: Ubuntu
BROWSER: Chrome

**Comment by alexiz10** [comment]
It seems this is happening because of multiple countries using the same country code. It looks like countries like Anguilla (+1 264) and Antigua and Barbuda (+1 268) are only grabbing the first number, therefore being shown as +1. I'm not sure if this is a problem with this package, aince this package is uaing [react-phone-number-input](https://www.npmjs.com/package/react-phone-number-input) under the hood, which then uses [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js) to get the country codes. The issue might be with `libphonenumber-js`.

**Comment by cove-cyril** [comment]
Bruh there's no problem with `libphonenumber-js` lmao

**Comment by cove-cyril** [comment]
I'm just using this as a workaround
```
<PhoneInput
    defaultCountry="US"
/>
```
